# NumPy for Numerical Computing

### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [ ]:
import numpy as np  # Import numpy library and assign an alias 'np'

# A. Create an ndarray object (A) with values from 1 to 100 in a nested Python List.
# You can choose the range from the given values (1-100).
A = np.array([[i for i in range(1, 101)]])  # Create a nested Python list containing values from 1 to 100,
                                            # then convert it into a numpy array using np.array().

# Accessing properties and methods of the ndarray object 'A':
print("Shape of A:", A.shape)  # Display the shape of array A using the 'shape' property.
print("Maximum value in A:", A.max())  # Find and print the maximum value in array A using the 'max()' method.
print("Sum of all values in A:", A.sum())  # Calculate and print the sum of all values in array A using the 'sum()' method.
print("Mean of all values in A:", A.mean())  # Calculate and print the mean of all values in array A using the 'mean()' method.

# Using numpy functions and passing the ndarray 'A':
print("Minimum value in A:", np.min(A))  # Find and print the minimum value in array A using the 'min()' function.

# B. Create a 5x5 integer-array filled with ones.
# Check its shape, size, and number of dimensions.
ones_array = np.ones((5, 5), dtype=int)  # Create a 5x5 array filled with ones using the 'ones()' function.
print("\nShape of ones_array:", ones_array.shape)  # Display the shape of ones_array.
print("Size of ones_array:", ones_array.size)  # Display the size (total number of elements) of ones_array.
print("Number of dimensions of ones_array:", ones_array.ndim)  # Display the number of dimensions of ones_array.

# C. Create an array of values from -5 to +5. Multiply each value by 2. Print the resulting array.
# Explanation: We use np.arange() to create an array of values from -5 to 5, then multiply each value by 2.
result_array = np.arange(-5, 6) * 2  # Create an array of values from -5 to 5 using np.arange() and multiply each value by 2.
print("\nResulting array after multiplication:", result_array)  # Print the resulting array.


Shape of A: (1, 100)
Maximum value in A: 100
Sum of all values in A: 5050
Mean of all values in A: 50.5
Minimum value in A: 1

Shape of ones_array: (5, 5)
Size of ones_array: 25
Number of dimensions of ones_array: 2

Resulting array after multiplication: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [ ]:
# Using an increment of 2, this code generates an array of 30 values between 1 and 100.
# then multiplies each array element by three before printing the finished array.

import numpy as np

#Make an array with 30 values that are grouped by two increments between 1 and 100.
arr = np.arange(1, 61, 2)

# Multiply the array by 3
result = arr * 3

# Print the result
print(result)



[  3   9  15  21  27  33  39  45  51  57  63  69  75  81  87  93  99 105
 111 117 123 129 135 141 147 153 159 165 171 177]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [ ]:
#A. A four-dimensional array of random integers in the range [0, 12] is produced using this code.
# It then retrieves the size, shape, and dimensions of the resultant array and prints it.


import numpy as np

# Create a four-dimensional array of random integers in the interval [0, 12]
arr = np.random.randint(0, 13, size=(3, 4, 5, 2))

# Print the resulting array
print("Resulting array:")
print(arr)

# Get the dimensions, shape, and size of the array
print("\nDimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)

# B. This code gets the maximum number for each dimension of the array and displays it.

# Get the maximum number for each dimension
max_values = [arr.max(axis=i) for i in range(arr.ndim)]
print("\nMaximum number for each dimension:")
for i, max_val in enumerate(max_values):
    print(f"Dimension {i+1}: {max_val}")

# C. This code multiplies each element of the array by 4.

# Multiply each array with 4
result = arr * 4

# An explanation of the process of multiplication
# The array's values are essentially scaled up by a factor of four by multiplying each element by 4.
# This operation is performed element-wise, which means that the value of each element is multiplied by 4 on its own.



Resulting array:
[[[[ 1 11]
   [11  7]
   [ 4  5]
   [ 0  6]
   [ 0  8]]

  [[ 6  3]
   [ 1  4]
   [ 8  8]
   [ 0 10]
   [ 1 10]]

  [[ 3  2]
   [ 0  2]
   [ 5  6]
   [ 3 11]
   [ 3  2]]

  [[ 8 10]
   [ 2 10]
   [ 2  7]
   [ 0  8]
   [12  3]]]


 [[[10 10]
   [ 4  1]
   [ 8  9]
   [ 1  0]
   [ 2  9]]

  [[10 11]
   [ 8  6]
   [ 9  3]
   [ 7  6]
   [ 6 10]]

  [[ 7  8]
   [ 6  1]
   [10  5]
   [11 12]
   [10  3]]

  [[ 1  4]
   [ 8  2]
   [ 2  8]
   [ 0  6]
   [ 0  3]]]


 [[[10  7]
   [ 8  6]
   [10  0]
   [ 5  3]
   [ 9  8]]

  [[ 2  1]
   [12  8]
   [ 5  7]
   [ 0  1]
   [ 9 11]]

  [[ 5  6]
   [ 8  3]
   [ 4  8]
   [ 2  5]
   [10  3]]

  [[ 8  6]
   [12 10]
   [ 2  0]
   [ 1 12]
   [11  5]]]]

Dimensions: 4
Shape: (3, 4, 5, 2)
Size: 120

Maximum number for each dimension:
Dimension 1: [[[10 11]
  [11  7]
  [10  9]
  [ 5  6]
  [ 9  9]]

 [[10 11]
  [12  8]
  [ 9  8]
  [ 7 10]
  [ 9 11]]

 [[ 7  8]
  [ 8  3]
  [10  8]
  [11 12]
  [10  3]]

 [[ 8 10]
  [12 10]
  [ 2  8]
  [ 1 12]
  [1